AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
  LambdaSubscriber:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TOPIC_ARN: !Ref SNSTopic
          BUCKET_NAME: !Ref S3EventStorage
      Policies:
        - SNSCrudPolicy:
            TopicName: !GetAtt SNSTopic.TopicName
        - S3CrudPolicy:
            BucketName: !Ref S3EventStorage
      Events:
        PubApi:
          Type: Api
          Properties:
            Path: /publish
            Method: POST
            RestApiId: !Ref ApiPublisher
  S3EventStorage:
    Type: AWS::S3::Bucket
Outputs:
  SNSTopic:
    Value: !Ref SNSTopic
    Description: The SNS topic your Lambda is subscribed to
  S3Bucket:
    Value: !Ref S3EventStorage
    Description: The S3 Bucket where you store your SNS events